#pragma once

#define CONTEXT_ANGLE (45.0f * 0.5f)
#define CONTEXT_RANGE 600.0f
#define CONTEXT_DIRECTION_THRESHOLD 0.9f

#define CONTEXT_HURT_THRESHOLD 0.5f
#define CONTEXT_DYING_THRESHOLD 0.1f

#define CONTEXT_TERRIFIED_THRESHOLD 0.8f
#define CONTEXT_SCARED_THRESHOLD 0.4f
#define CONTEXT_SPOOKED_THRESHOLD 0.2f
